### ISSUE TITLE
GitHub Latest broken after site change

### ISSUE THREAD

**Issue by jerone** [Ede123/userscripts#14]
It looks like GitHub changed its site again and broke GitHub Latest userscript.

This fixed it for me:
```diff
@@ -28,7 +28,7 @@

 	var reponav = document.getElementsByClassName("reponav");
 	if (reponav && (reponav = reponav[0])) {
-		var button = reponav.children[1].firstElementChild.cloneNode(true);
+		var button = reponav.firstElementChild.children[1].firstElementChild.cloneNode(true);
 		button.id = "latest-button"
 		button.href += "?sort=updated";
 		button.style.float = "right";
```

**Comment by Ede123** [comment]
Thanks, fixed!

**Comment by jerone** [comment]
Your fix didn't work as intended for me.
That's probably because `reponav.children[1]` element does exists, but it's the wrong element to target and will fail further in the code.

> ERROR: Execution of script 'GitHub Latest' failed! button.firstElementChild.firstElementChild is null
> GitHub Latest.user.js:1:274

It looks like GitHub added an extra element in the `nav`.

![image](https://user-images.githubusercontent.com/55841/80642364-a5223080-8a66-11ea-8fad-6bbb506c32c3.png)

**Comment by jerone** [comment]
Refined GitHub's solution might be interesting: https://github.com/sindresorhus/refined-github/blob/5d5691729e9210a52c78e7fe96c780a7482b1ad2/source/features/releases-tab.tsx#L54-L63

**Comment by Ede123** [comment]
I'm not seeing a `reponav.children[1]`, but we were certainly adding the button in the wrong place (it effectively became `reponav.children[1]`).

Changed now in f5da3d832ecedd141575f5cdd56a4045f29af0af. It still seems awfully fragile, but I don't really want to put much more effort into it right now (especially considering it will probably still be broken by a GitLab update sooner rather than later).

Let me know if any functional issues remain.

**Comment by jerone** [comment]
Last commit works. Thanks!
